---
fixtures:
  repositories:
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "epel": "git://github.com/stahnma/puppet-module-epel.git"
    "nodejs": "git://github.com/voxpupuli/puppet-nodejs.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"

  symlinks:
    statsd: "#{source_dir}"
