---
fixtures:
  repositories:
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
      ref: 2.1.1
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
      ref: 1.3.0
    nodejs:
      repo: git://github.com/voxpupuli/puppet-nodejs.git
      ref: 2.3.0
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.16.0           

  symlinks:
    statsd: "#{source_dir}"
